from scadwright import emit_str
from scadwright.primitives import cube
def test_pretty_default_has_indentation():
    tree = cube([1, 2, 3]).translate([0, 0, 5])
    out = emit_str(tree)
    assert "\n" in out
    assert "    cube" in out  # 4-space indent on nested cube


def test_compact_mode_no_newlines():
    tree = cube([1, 2, 3]).translate([0, 0, 5])
    out = emit_str(tree, pretty=False)
    assert "\n" not in out
    assert "translate" in out and "cube" in out


def test_debug_adds_source_comments():
    tree = cube([1, 2, 3])
    out = emit_str(tree, debug=True)
    assert "// " in out
    assert "test_emit_modes.py" in out


def test_debug_off_has_no_source_comments():
    """debug=False must not emit source-location comments. The file still
    has its `// Generated by scadwright ...` banner, but no per-node source
    comments tagged with a file path."""
    tree = cube([1, 2, 3])
    out = emit_str(tree)
    # The banner is fine; what we forbid is per-node source annotations.
    assert "cube" not in next(
        (ln for ln in out.splitlines() if ln.lstrip().startswith("//") and ".py:" in ln),
        "",
    )
    assert ".py:" not in out
