"""Extended shape library — higher-level shapes built on the primitives."""

from scadwright.shapes.curves import (
    Helix,
    Spring,
    bezier_path,
    catmull_rom_path,
    circle_profile,
    helix_path,
    path_extrude,
)
from scadwright.shapes.ecosystem import ExtrusionProfile, GridfinityBase, GridfinityBin
from scadwright.shapes.fasteners import (
    Bolt,
    CaptiveNutPocket,
    HeatSetPocket,
    HexNut,
    SquareNut,
    Standoff,
    clearance_hole,
    get_insert_spec,
    get_nut_spec,
    get_screw_spec,
    tap_hole,
)
from scadwright.shapes.mechanical import (
    Bearing,
    DShaft,
    GT2Pulley,
    HTDPulley,
    KeyedShaft,
)
from scadwright.shapes.gears import (
    BevelGear,
    Rack,
    RingGear,
    SpurGear,
    Worm,
    WormGear,
    gear_dimensions,
)
from scadwright.shapes.fillets import (
    ChamferMask,
    ChamferedBox,
    Counterbore,
    Countersink,
    FilletMask,
)
from scadwright.shapes.print_shapes import (
    EmbossedLabel,
    GridPanel,
    GripTab,
    HoneycombPanel,
    SnapHook,
    TabSlot,
    TextPlate,
    TriGridPanel,
    VentSlots,
)
from scadwright.shapes.polyhedra import (
    Dodecahedron,
    Dome,
    Icosahedron,
    Octahedron,
    Prism,
    Pyramid,
    SphericalCap,
    Tetrahedron,
    Torus,
)
from scadwright.shapes.three_d import FilletRing, Funnel, RoundedBox, Tube, UShapeChannel
from scadwright.shapes.two_d import (
    Arc,
    RoundedEndsArc,
    RoundedSlot,
    Sector,
    regular_polygon,
    rounded_rect,
    rounded_square,
)

__all__ = [
    # Components (capitalized)
    "Arc",
    "Bearing",
    "BevelGear",
    "Bolt",
    "CaptiveNutPocket",
    "ChamferMask",
    "ChamferedBox",
    "Counterbore",
    "Countersink",
    "DShaft",
    "Dodecahedron",
    "Dome",
    "EmbossedLabel",
    "ExtrusionProfile",
    "FilletMask",
    "FilletRing",
    "Funnel",
    "GridPanel",
    "GridfinityBase",
    "GridfinityBin",
    "GripTab",
    "GT2Pulley",
    "HTDPulley",
    "HeatSetPocket",
    "Helix",
    "HexNut",
    "HoneycombPanel",
    "Icosahedron",
    "KeyedShaft",
    "Octahedron",
    "Prism",
    "Pyramid",
    "Rack",
    "SphericalCap",
    "RingGear",
    "RoundedBox",
    "RoundedEndsArc",
    "RoundedSlot",
    "Sector",
    "SnapHook",
    "SpurGear",
    "Spring",
    "SquareNut",
    "Standoff",
    "TabSlot",
    "Tetrahedron",
    "TextPlate",
    "Torus",
    "TriGridPanel",
    "Tube",
    "UShapeChannel",
    "VentSlots",
    "Worm",
    "WormGear",
    # Functions (lowercase)
    "gear_dimensions",
    "bezier_path",
    "catmull_rom_path",
    "circle_profile",
    "clearance_hole",
    "get_insert_spec",
    "get_nut_spec",
    "get_screw_spec",
    "helix_path",
    "path_extrude",
    "regular_polygon",
    "rounded_rect",
    "rounded_square",
    "tap_hole",
]
