// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    cylinder(h=10, r=15, center=false);

    translate([11.8653, -1.79326, 9.99]) {
        multmatrix([[0.149438, 0.988771, 0, 0], [0.988771, -0.149438, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                translate([-0.9, -1.5, 0]) {
                    text("M", size=3);
                }
            }
        }
    }

    translate([12, 0, 9.99]) {
        multmatrix([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                translate([-0.9, -1.5, 0]) {
                    text("A", size=3);
                }
            }
        }
    }

    translate([11.8653, 1.79326, 9.99]) {
        multmatrix([[-0.149438, 0.988771, 0, 0], [0.988771, 0.149438, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                translate([-0.9, -1.5, 0]) {
                    text("X", size=3);
                }
            }
        }
    }
}
