// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    cube([50, 30, 3], center=false);

    translate([25, 15, 2.5]) {
        linear_extrude(height=1, center=false) {
            union() {
                translate([0, 3, 0]) {
                    text("LINE 1", size=5, halign="center", valign="center");
                }
                translate([0, -3, 0]) {
                    text("LINE 2", size=5, halign="center", valign="center");
                }
            }
        }
    }
}
