// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    // Funnel
    //  bot_od = 20  (input)
    //  h      = 20  (input)
    //  thk    = 2  (input)
    //  top_od = 10  (input)
    difference() {
        cylinder(h=20, r1=10, r2=5, center=false);
        translate([0, 0, -0.01]) {
            scale([1, 1, 1.001]) {
                cylinder(h=20, r1=8, r2=3, center=false);
            }
        }
    }

    translate([6.91059, -1.11523, 10]) {
        multmatrix([[0.159318, -0.239438, 0.957751, 0], [0.987227, 0.0386403, -0.154561, 0], [0, 0.970143, 0.242536, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("L", size=4);
                }
            }
        }
    }

    translate([6.91059, 1.11523, 10]) {
        multmatrix([[-0.159318, -0.239438, 0.957751, 0], [0.987227, -0.0386403, 0.154561, 0], [0, 0.970143, 0.242536, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("O", size=4);
                }
            }
        }
    }
}
