// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    // Tube
    //  h   = 20  (input)
    //  od  = 20  (input)
    //  thk = 2  (input)
    difference() {
        cylinder(h=20, r=10, center=false);
        translate([0, 0, -0.01]) {
            scale([1, 1, 1.001]) {
                cylinder(h=20, r=8, center=false);
            }
        }
    }

    translate([7.92006, -1.197, 10]) {
        multmatrix([[-0.149438, 0, -0.988771, 0], [-0.988771, 0, 0.149438, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                translate([-1.2, 0, 0]) {
                    text("I", size=4);
                }
            }
        }
    }

    translate([7.92006, 1.197, 10]) {
        multmatrix([[0.149438, 0, -0.988771, 0], [-0.988771, 0, -0.149438, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                translate([-1.2, 0, 0]) {
                    text("N", size=4);
                }
            }
        }
    }
}
