// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    // Funnel
    //  bot_od = 20  (input)
    //  h      = 20  (input)
    //  thk    = 2  (input)
    //  top_od = 10  (input)
    difference() {
        cylinder(h=20, r1=10, r2=5, center=false);
        translate([0, 0, -0.01]) {
            scale([1, 1, 1.001]) {
                cylinder(h=20, r1=8, r2=3, center=false);
            }
        }
    }

    translate([7.39433, -1.19329, 10]) {
        multmatrix([[0.159318, 0, 0.987227, 0], [0.987227, 0, -0.159318, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                text("L", size=4, halign="center", valign="center");
            }
        }
    }

    translate([7.39433, 1.19329, 10]) {
        multmatrix([[-0.159318, 0, 0.987227, 0], [0.987227, 0, 0.159318, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.41, center=false) {
                text("O", size=4, halign="center", valign="center");
            }
        }
    }
}
