// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    cylinder(h=30, r=12, center=false);

    translate([11.4425, -1.14808, 17.4]) {
        multmatrix([[0.0998334, 0, 0.995004, 0], [0.995004, 0, -0.0998334, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("A", size=4);
                }
            }
        }
    }

    translate([11.4425, 1.14808, 17.4]) {
        multmatrix([[-0.0998334, 0, 0.995004, 0], [0.995004, 0, 0.0998334, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("B", size=4);
                }
            }
        }
    }

    translate([11.4425, -1.14808, 12.6]) {
        multmatrix([[0.0998334, 0, 0.995004, 0], [0.995004, 0, -0.0998334, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("C", size=4);
                }
            }
        }
    }

    translate([11.4425, 1.14808, 12.6]) {
        multmatrix([[-0.0998334, 0, 0.995004, 0], [0.995004, 0, 0.0998334, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) {
            linear_extrude(height=0.9, center=false) {
                translate([-1.2, -2, 0]) {
                    text("D", size=4);
                }
            }
        }
    }
}
