// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    cube([40, 30, 5], center=false);

    translate([28, 10, 4.99]) {
        linear_extrude(height=0.41, center=false) {
            text("LO", size=4, halign="center", valign="center");
        }
    }
}
