// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 24;

// _Plate
union() {
    cube([20, 20, 2], center=false);

    translate([5, 5, 2]) {
        // _Peg
        cylinder(h=5, r=1, center=false);
    }

    translate([15, 15, 2]) {
        // _Peg
        cylinder(h=5, r=1, center=false);
    }
}
