// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

module chamfer_top_655a5176(depth) {
    minkowski() {
        children();
        sphere(r=1, $fn=8);
    }
}

union() {
    chamfer_top_655a5176(depth=1) {
        cube([10, 10, 5], center=false);
    }

    chamfer_top_655a5176(depth=1) {
        translate([15, 0, 0]) {
            cube([6, 6, 8], center=false);
        }
    }
}
