// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 32;

difference() {
    translate([-20, -20, 0]) {
        cube([40, 40, 20], center=false);
    }
    translate([10, 0, 0]) {
        cylinder(h=22, r=3, center=false);
    }
    translate([-10, 0, 0]) {
        cylinder(h=22, r=3, center=false);
    }
}
