// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 48;

union() {
    // Widget
    difference() {
        translate([-20, -20, 0]) {
            cube([40, 40, 20], center=false);
        }
        translate([15, 0, 0]) {
            cylinder(h=22, r=3, center=true);
        }
        translate([-15, 0, 0]) {
            cylinder(h=22, r=3, center=true);
        }
    }

    color("red") {
        translate([50, 0, 0]) {
            // Widget
            difference() {
                translate([-20, -20, 0]) {
                    cube([40, 40, 20], center=false);
                }
                translate([15, 0, 0]) {
                    cylinder(h=22, r=3, center=true);
                }
                translate([-15, 0, 0]) {
                    cylinder(h=22, r=3, center=true);
                }
            }
        }
    }
}
