// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 12;

hull() {
    cube([10, 10, 1], center=false);
    translate([5, 5, 0]) {
        cylinder(h=10, r=1, center=false);
    }
}
