// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 16;

union() {
    cylinder(h=10, r=2, center=false);

    translate([8, 0, 0]) {
        cylinder(h=10, r=2, center=false);
    }

    translate([16, 0, 0]) {
        cylinder(h=10, r=2, center=false);
    }

    translate([24, 0, 0]) {
        cylinder(h=10, r=2, center=false);
    }

    translate([32, 0, 0]) {
        cylinder(h=10, r=2, center=false);
    }
}
