// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 8;

minkowski() {
    translate([-5, -5, 0]) {
        cube([10, 10, 2], center=false);
    }
    sphere(r=1);
}
