// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    translate([5, 0, 0]) {
        cube([10, 5, 2], center=false);
    }

    mirror([1, 0, 0]) {
        translate([5, 0, 0]) {
            cube([10, 5, 2], center=false);
        }
    }
}
