// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 12;

union() {
    translate([5, 0, 0]) {
        cube([5, 5, 5], center=false);
    }

    translate([7, 0, 5]) {
        sphere(r=2);
    }

    mirror([1, 0, 0]) {
        translate([5, 0, 0]) {
            cube([5, 5, 5], center=false);
        }
    }

    mirror([1, 0, 0]) {
        translate([7, 0, 5]) {
            sphere(r=2);
        }
    }
}
