// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 12;

union() {
    hull() {
        cube([3, 3, 3], center=true);
        translate([10, 0, 0]) {
            sphere(r=1.5);
        }
    }

    hull() {
        cube([3, 3, 3], center=true);
        translate([0, 10, 0]) {
            sphere(r=1.5);
        }
    }

    hull() {
        cube([3, 3, 3], center=true);
        translate([0, 0, 10]) {
            sphere(r=1.5);
        }
    }
}
