// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

polyhedron(points=[[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]], faces=[[0, 1, 2], [0, 2, 3], [0, 3, 1], [1, 3, 2]], convexity=2);
