// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

union() {
    translate([10, 0, 0]) {
        cube([5, 1, 10], center=false);
    }

    rotate(a=90, v=[0, 0, 1]) {
        translate([10, 0, 0]) {
            cube([5, 1, 10], center=false);
        }
    }

    rotate(a=180, v=[0, 0, 1]) {
        translate([10, 0, 0]) {
            cube([5, 1, 10], center=false);
        }
    }

    rotate(a=270, v=[0, 0, 1]) {
        translate([10, 0, 0]) {
            cube([5, 1, 10], center=false);
        }
    }
}
