// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 8;

union() {
    hull() {
        translate([0, 0, 0]) {
            sphere(r=1);
        }
        translate([5, 5, 0]) {
            sphere(r=1);
        }
    }

    hull() {
        translate([5, 5, 0]) {
            sphere(r=1);
        }
        translate([10, 5, 5]) {
            sphere(r=1);
        }
    }

    hull() {
        translate([10, 5, 5]) {
            sphere(r=1);
        }
        translate([10, 0, 10]) {
            sphere(r=1);
        }
    }
}
