// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

polygon(points=[[5, 0], [2.5, 4.33013], [-2.5, 4.33013], [-5, 6.12323e-16], [-2.5, -4.33013], [2.5, -4.33013]]);
