// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 16;

linear_extrude(height=3, center=false) {
    // RoundedSlot
    union() {
        square([16, 4], center=true);
        translate([8, 0, 0]) {
            circle(r=2);
        }
        translate([-8, 0, 0]) {
            circle(r=2);
        }
    }
}
