// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

// UShapeChannel
difference() {
    cube([14, 20, 10], center=false);
    translate([2, -0.01, 2]) {
        cube([10, 20.02, 8.02], center=false);
    }
}
