// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 24;

// Sector
intersection() {
    circle(r=10);
    polygon(points=[[0, 0], [20, 0], [10, 17.3205]]);
}
