// Generated by scadwright. Do not hand-edit —
// edit the Python source and regenerate.

$fn = 24;

// FilletRing
difference() {
    cylinder(h=5.7735, r1=10, r2=0, center=false);
    translate([0, 0, -0.02]) {
        cylinder(h=2.92675, r=5, center=false);
    }
}
